name: hts-venv
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://conda.anaconda.org/intel
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - expat=2.7.1
  - ffmpeg=4.3.2
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - intel-openmp=2025.0.0
  - lame=3.100
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libxcb=1.17.0
  - mkl=2025.0.0
  - ncurses=6.5
  - nettle=3.6
  - openh264=2.1.1
  - openssl=3.0.17
  - pip=24.0
  - pthread-stubs=0.3
  - python=3.9.23
  - readline=8.3
  - sqlite=3.50.2
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - x264=1!161.3030
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - anyio==4.10.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - audioread==3.0.1
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - cachetools==5.5.2
      - certifi==2025.8.3
      - cffi==1.17.1
      - charset-normalizer==3.4.3
      - comm==0.2.3
      - cycler==0.12.1
      - debugpy==1.8.16
      - decorator==5.2.1
      - defusedxml==0.7.1
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastjsonschema==2.21.2
      - ffmpeg-python==0.2.0
      - filelock==3.19.1
      - fonttools==4.59.1
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - future==1.0.0
      - gdown==5.2.0
      - google-auth==2.40.3
      - google-auth-oauthlib==0.4.6
      - grpcio==1.74.0
      - h11==0.16.0
      - h5py==3.6.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - idna==3.10
      - importlib-metadata==8.7.0
      - ipykernel==6.30.1
      - ipython==8.18.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.6
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - lark==1.2.2
      - librosa==0.8.1
      - lightning-utilities==0.15.2
      - llvmlite==0.43.0
      - markdown==3.8.2
      - markupsafe==3.0.2
      - matplotlib==3.5.1
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - mpmath==1.3.0
      - multidict==6.6.4
      - musdb==0.4.3
      - museval==0.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - notebook==7.4.5
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.22.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - oauthlib==3.3.1
      - overrides==7.7.0
      - packaging==25.0
      - pandas==1.4.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.3.0
      - platformdirs==4.3.8
      - pooch==1.8.2
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==3.20.3
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyaml==25.7.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydeprecate==0.3.1
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - pytorch-lightning==1.5.9
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==27.0.1
      - referencing==0.36.2
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - resampy==0.4.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.27.0
      - rsa==4.9.1
      - scikit-learn==1.0.2
      - scipy==1.7.3
      - send2trash==1.8.3
      - setuptools==59.5.0
      - simplejson==3.20.1
      - six==1.17.0
      - sniffio==1.3.1
      - soundfile==0.10.3.post1
      - soupsieve==2.7
      - stack-data==0.6.3
      - stempeg==0.2.4
      - sympy==1.14.0
      - tensorboard==2.8.0
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tomli==2.2.1
      - torch==1.13.0
      - torchaudio==0.13.0
      - torchcontrib==0.0.2
      - torchlibrosa==0.0.9
      - torchmetrics==0.4.1
      - tornado==6.5.2
      - tqdm==4.62.3
      - traitlets==5.14.3
      - triton==3.4.0
      - types-python-dateutil==2.9.0.20250809
      - typing-extensions==4.14.1
      - uri-template==1.3.0
      - urllib3==2.5.0
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - wget==3.2
      - widgetsnbextension==4.0.14
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /home/sergio/miniconda3/envs/hts-venv
